<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="fb_motor_2" Id="{23b1ed52-99f0-496b-ac35-592cfa42d18c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK fb_motor_2
VAR_INPUT
	bStart, bStop : BOOL;
	
END_VAR
VAR_OUTPUT
	bStatus : BOOL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>