<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN" Id="{5d7ce718-129a-4ede-b2b8-37034ae92ca0}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbMotor1: fb_motor;
	fbmotor2: fb_motor;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
fbMotor1(bStart:= true, bStop:= true, bStatus=> );]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>